parameters:
#    myapp_filmotheque.example.class: Myapp\FilmothequeBundle\Example

services:
#    myapp_filmotheque.example:
#        class: %myapp_filmotheque.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
