<?php

namespace AppProd\GedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * prestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prestaRepository extends EntityRepository
{
}
