<?php

namespace Myapp\FilmothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * infopersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class infopersRepository extends EntityRepository
{
}
